In [5]:
sequences = [ ['a', 1], ['b', 2], ['c',3] ]
X,y = zip(*sequences) # *를 추가해야 에러가 나지 않음
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [9]:
#데이터 프레임을 이용하여 분리하기
import pandas as pd

values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [12]:
#데이터 프레임은 열의 이름으로 각 열에 접근이 가능하다.

X = df['메일 본문']
y = df['스팸 메일 유무']

print(X)

0          당신에게 드리는 마지막 혜택!
1      내일 뵐 수 있을지 확인 부탁드...
2      도연씨. 잘 지내시죠? 오랜만입...
3    (광고) AI로 주가를 예측할 수 있다!
Name: 메일 본문, dtype: object


In [19]:
# Numpy를 이용하여 분리하기
import numpy as np
ar = np.arange(0,16).reshape((4,4))
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [20]:
X = ar[:, :3]
print(X)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [22]:
y = ar[:,3]
print(y)

[ 3  7 11 15]


In [32]:
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5,2)), range(5) 
print(X)
print(list(y))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [33]:
X_train, X_test, y_train, y_test = train_test_split ( X, y, test_size = 0.33, random_state = 1234) # 1/3 만 test 데이터로 지정한 것
print('X_train \n', X_train)
print('\n X_test \n', X_test)
print('y_train \n', y_train)
print('\n y_test \n', y_test)

X_train 
 [[2 3]
 [4 5]
 [6 7]]

 X_test 
 [[8 9]
 [0 1]]
y_train 
 [1, 2, 3]

 y_test 
 [4, 0]


In [ ]:
#수동으로 분리하기
import 